In [1]:
import numpy as np

In [7]:
X = np.random.randn(4,4)

In [8]:
X

array([[-1.12201926,  0.62668281, -0.38312157, -0.54563296],
       [ 0.28907648,  0.93042067, -0.72031917, -0.33685498],
       [-0.47989186,  1.79267819, -0.11974564,  0.31709946],
       [ 0.11545699,  1.4342302 , -0.3448477 ,  1.30176033]])

In [11]:
X.reshape(-1,8)

array([[-1.12201926,  0.62668281, -0.38312157, -0.54563296,  0.28907648,
         0.93042067, -0.72031917, -0.33685498],
       [-0.47989186,  1.79267819, -0.11974564,  0.31709946,  0.11545699,
         1.4342302 , -0.3448477 ,  1.30176033]])

In [13]:
np.arange(0, 11, 10/101)

array([ 0.        ,  0.0990099 ,  0.1980198 ,  0.2970297 ,  0.3960396 ,
        0.4950495 ,  0.59405941,  0.69306931,  0.79207921,  0.89108911,
        0.99009901,  1.08910891,  1.18811881,  1.28712871,  1.38613861,
        1.48514851,  1.58415842,  1.68316832,  1.78217822,  1.88118812,
        1.98019802,  2.07920792,  2.17821782,  2.27722772,  2.37623762,
        2.47524752,  2.57425743,  2.67326733,  2.77227723,  2.87128713,
        2.97029703,  3.06930693,  3.16831683,  3.26732673,  3.36633663,
        3.46534653,  3.56435644,  3.66336634,  3.76237624,  3.86138614,
        3.96039604,  4.05940594,  4.15841584,  4.25742574,  4.35643564,
        4.45544554,  4.55445545,  4.65346535,  4.75247525,  4.85148515,
        4.95049505,  5.04950495,  5.14851485,  5.24752475,  5.34653465,
        5.44554455,  5.54455446,  5.64356436,  5.74257426,  5.84158416,
        5.94059406,  6.03960396,  6.13861386,  6.23762376,  6.33663366,
        6.43564356,  6.53465347,  6.63366337,  6.73267327,  6.83

In [16]:
np.linspace(0,10,101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [17]:
arr=np.arange(0,11)

In [18]:
arr[1:5]

array([1, 2, 3, 4])

In [19]:
arr[:5]

array([0, 1, 2, 3, 4])

In [22]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [23]:
temp =arr[0]

In [24]:
temp

0

In [25]:
temp+10

10

In [26]:
temp =10

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr_2nd = np.array([[11,12,13],[21,22,23],[31,32,33]])

In [40]:
arr_2nd.shape

(3, 3)

In [42]:
arr_2nd[1]

array([21, 22, 23])

In [45]:
arr_2nd[1,1]

22

In [46]:
arr=np.arange(1,11)

In [47]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [49]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [50]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [62]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr.sum()

55

In [65]:
arr.max()

10

In [67]:
arr.var()

8.25

In [68]:
a

NameError: name 'a' is not defined

In [69]:
arr_2nd

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [70]:
arr_2nd.mean()

22.0

In [76]:
arr_2nd.sum(axis=0)

array([63, 66, 69])